#!/usr/bin/env ruby
# simple serial terminal
require 'rubygems'
gem 'serialport','>=1.0.4'
require 'serialport'
require 'eventmachine'
require 'ArgsParser'

parser = ArgsParser.parser
parser.bind(:help, :h, 'show help')
parser.comment(:bps, 'bit per second', 9600)
parser.comment(:bit, 'bit(7-9)', 8)
parser.comment(:stopbit, 'stopbit', 1)
parser.comment(:parity, 'parity bit', 0)
serial_device, params = parser.parse(ARGV)

if !serial_device or parser.has_option(:help)
  puts parser.help
  if RUBY_PLATFORM =~ /mswin|mingw|cygwin|bccwin/
    puts 'e.g. serialterm COM1'
    puts '     serialterm COM1 -bps 9600 -bit 8 -stopbit 1 -parity 0'
  else
  puts 'e.g. serialterm /dev/tty.your-device'
    puts '     serialterm /dev/tty.your-device -bps 9600 -bit 8 -stopbit 1 -parity 0'
  end
  exit 1
end

begin
  sp = SerialPort.new(serial_device, params[:bps].to_i, params[:bit].to_i, params[:stopbit].to_i, params[:parity].to_i) # 9600bps, 8bit, stopbit 1, parity none
rescue
end
EventMachine::run do

  EventMachine::defer do
    loop do
      line = sp.gets rescue exit(1)
      puts line
    end
  end
  
  EventMachine::defer do
    loop do
      line = gets
      sp.puts line rescue exit(1)
    end
  end

end

sp.close

